library(tarchetypes)
library(conflicted)
library(tidyverse)
library(lubridate)
library(jsonlite)
library(targets)
library(httpuv)
library(duckdb)
library(httr2)
library(arrow)
library(pins)
library(glue)
library(fs)
library(sf)

conflict_prefer("filter", "dplyr")
